{{- if not .Values.operator.adminExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamweld.adminSecretName" . }}
  labels:
    {{- include "streamweld.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ include "streamweld.adminToken" . | b64enc | quote }}
{{- end }}
