{{- if and (or .Values.redis.enabled (eq .Values.journal.backend "redis")) (not .Values.journal.redis.existingSecret) }}
{{- $redisPassword := include "streamweld.redisPassword" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "streamweld.redisSecretName" . }}
  labels:
    {{- include "streamweld.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  {{- if .Values.journal.redis.url }}
  {{ .Values.journal.redis.secretKey }}: {{ .Values.journal.redis.url | b64enc | quote }}
  {{- else if .Values.redis.auth.enabled }}
  {{ .Values.journal.redis.secretKey }}: {{ printf "redis://:%s@%s:6379/0" $redisPassword (include "streamweld.redisName" .) | b64enc | quote }}
  {{- else }}
  {{ .Values.journal.redis.secretKey }}: {{ printf "redis://%s:6379/0" (include "streamweld.redisName" .) | b64enc | quote }}
  {{- end }}
  {{- if and .Values.redis.enabled .Values.redis.auth.enabled }}
  redis-password: {{ $redisPassword | b64enc | quote }}
  {{- end }}
{{- end }}
