// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all receiver fields into out.
func (in *BackendPoolSpec) DeepCopyInto(out *BackendPoolSpec) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
}

// DeepCopy returns an independent copy of the receiver.
func (in *BackendPoolSpec) DeepCopy() *BackendPoolSpec {
	if in == nil {
		return nil
	}
	out := new(BackendPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all receiver fields into out.
func (in *BackendStatus) DeepCopyInto(out *BackendStatus) {
	*out = *in
	if in.LastProbedAt != nil {
		out.LastProbedAt = in.LastProbedAt.DeepCopy()
	}
}

// DeepCopy returns an independent copy of the receiver.
func (in *BackendStatus) DeepCopy() *BackendStatus {
	if in == nil {
		return nil
	}
	out := new(BackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all receiver fields into out.
func (in *InferenceRouteSpec) DeepCopyInto(out *InferenceRouteSpec) {
	*out = *in
	in.Backends.DeepCopyInto(&out.Backends)
}

// DeepCopy returns an independent copy of the receiver.
func (in *InferenceRouteSpec) DeepCopy() *InferenceRouteSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all receiver fields into out.
func (in *InferenceRouteStatus) DeepCopyInto(out *InferenceRouteStatus) {
	*out = *in
	if in.TemplateProbedAt != nil {
		out.TemplateProbedAt = in.TemplateProbedAt.DeepCopy()
	}
	if in.Backends != nil {
		out.Backends = make([]BackendStatus, len(in.Backends))
		for index := range in.Backends {
			in.Backends[index].DeepCopyInto(&out.Backends[index])
		}
	}
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for index := range in.Conditions {
			in.Conditions[index].DeepCopyInto(&out.Conditions[index])
		}
	}
}

// DeepCopy returns an independent copy of the receiver.
func (in *InferenceRouteStatus) DeepCopy() *InferenceRouteStatus {
	if in == nil {
		return nil
	}
	out := new(InferenceRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all receiver fields into out.
func (in *InferenceRoute) DeepCopyInto(out *InferenceRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns an independent copy of the receiver.
func (in *InferenceRoute) DeepCopy() *InferenceRoute {
	if in == nil {
		return nil
	}
	out := new(InferenceRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns an independent runtime.Object copy.
func (in *InferenceRoute) DeepCopyObject() runtime.Object {
	if copy := in.DeepCopy(); copy != nil {
		return copy
	}
	return nil
}

// DeepCopyInto copies all receiver fields into out.
func (in *InferenceRouteList) DeepCopyInto(out *InferenceRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]InferenceRoute, len(in.Items))
		for index := range in.Items {
			in.Items[index].DeepCopyInto(&out.Items[index])
		}
	}
}

// DeepCopy returns an independent copy of the receiver.
func (in *InferenceRouteList) DeepCopy() *InferenceRouteList {
	if in == nil {
		return nil
	}
	out := new(InferenceRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns an independent runtime.Object copy.
func (in *InferenceRouteList) DeepCopyObject() runtime.Object {
	if copy := in.DeepCopy(); copy != nil {
		return copy
	}
	return nil
}

// DeepCopyInto copies all receiver fields into out.
func (in *DurabilityPolicySpec) DeepCopyInto(out *DurabilityPolicySpec) {
	*out = *in
	if in.MaxMigrations != nil {
		out.MaxMigrations = new(int32)
		*out.MaxMigrations = *in.MaxMigrations
	}
	if in.MaxMigrationTokens != nil {
		out.MaxMigrationTokens = new(int64)
		*out.MaxMigrationTokens = *in.MaxMigrationTokens
	}
	if in.MaxStreamDuration != nil {
		out.MaxStreamDuration = new(metav1.Duration)
		*out.MaxStreamDuration = *in.MaxStreamDuration
	}
	if in.OrphanTimeout != nil {
		out.OrphanTimeout = new(metav1.Duration)
		*out.OrphanTimeout = *in.OrphanTimeout
	}
	if in.SeamWindowBytes != nil {
		out.SeamWindowBytes = new(int32)
		*out.SeamWindowBytes = *in.SeamWindowBytes
	}
	if in.JournalTTL != nil {
		out.JournalTTL = new(metav1.Duration)
		*out.JournalTTL = *in.JournalTTL
	}
}

// DeepCopy returns an independent copy of the receiver.
func (in *DurabilityPolicySpec) DeepCopy() *DurabilityPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DurabilityPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all receiver fields into out.
func (in *DurabilityPolicyStatus) DeepCopyInto(out *DurabilityPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		out.Conditions = make([]metav1.Condition, len(in.Conditions))
		for index := range in.Conditions {
			in.Conditions[index].DeepCopyInto(&out.Conditions[index])
		}
	}
}

// DeepCopy returns an independent copy of the receiver.
func (in *DurabilityPolicyStatus) DeepCopy() *DurabilityPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DurabilityPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all receiver fields into out.
func (in *DurabilityPolicy) DeepCopyInto(out *DurabilityPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns an independent copy of the receiver.
func (in *DurabilityPolicy) DeepCopy() *DurabilityPolicy {
	if in == nil {
		return nil
	}
	out := new(DurabilityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns an independent runtime.Object copy.
func (in *DurabilityPolicy) DeepCopyObject() runtime.Object {
	if copy := in.DeepCopy(); copy != nil {
		return copy
	}
	return nil
}

// DeepCopyInto copies all receiver fields into out.
func (in *DurabilityPolicyList) DeepCopyInto(out *DurabilityPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]DurabilityPolicy, len(in.Items))
		for index := range in.Items {
			in.Items[index].DeepCopyInto(&out.Items[index])
		}
	}
}

// DeepCopy returns an independent copy of the receiver.
func (in *DurabilityPolicyList) DeepCopy() *DurabilityPolicyList {
	if in == nil {
		return nil
	}
	out := new(DurabilityPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns an independent runtime.Object copy.
func (in *DurabilityPolicyList) DeepCopyObject() runtime.Object {
	if copy := in.DeepCopy(); copy != nil {
		return copy
	}
	return nil
}
